[workspace]
channels = ["conda-forge"]
name = "mvp"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[tasks.start]
depends-on = [ "stage-1-equilibrium", "stage-2-boozer", "stage-3-neoclassical"]

[dependencies]

[feature.stage-1.dependencies]
numpy = ">=2.4.3,<3"
jax = ">=0.9.1,<0.10"
netcdf4 = ">=1.7.4,<2"

[feature.stage-1.pypi-dependencies]
vmec-jax = { git = "https://github.com/uwplasma/vmec_jax", rev = "cfdf674b0ca213b3b97244b0cf0273d481ec37fd" }

[feature.stage-1.tasks.stage-1-equilibrium]
cmd = "vmec_jax stage1-equilibrium/vmec_jax/input/input.HSX_QHS_vacuum_ns201"

[feature.stage-2.dependencies]
numpy = ">=2.4.3,<3"
scipy = ">=1.17.1,<2"
jax = ">=0.9.1,<0.10"
netcdf4 = ">=1.7.4,<2"
matplotlib = ">=3.10.8,<4"
plotly = ">=6.6.0,<7"

[feature.stage-2.pypi-dependencies]
booz-xform-jax = { git = "https://github.com/uwplasma/booz_xform_jax.git", rev = "1f206597f2f28436e0e2124160c13de9ae63b2ea" }

[feature.stage-2.tasks.stage-2-boozer]
cmd = "python stage2-boozer/example.py"

[feature.stage-3.dependencies]
numpy = ">=2.4.3,<3"
scipy = ">=1.17.1,<2"
jax = ">=0.9.1,<0.10"
h5py = ">=3.16.0,<4"

[feature.stage-3.pypi-dependencies]
sfincs-jax = { git = "https://github.com/uwplasma/sfincs_jax", rev = "de50abd2ee9063176728805288e8bafe8e83cbc3" }

[feature.stage-3.tasks.stage-3-neoclassical]
cmd = "sfincs_jax stage3-neoclassical/sfincs_jax/input/input.HSX_QHS_vacuum_ns201"

[feature.cuda]
platforms = ["linux-64"]
[feature.cuda.system-requirements]
cuda = "12"

[environments]
stage-1 = {features = ["stage-1"], no-default-feature = true }
stage-1-gpu = {features = ["stage-1", "cuda"], no-default-feature = true }
stage-2 = {features = ["stage-2"], no-default-feature = true }
stage-2-gpu = {features = ["stage-2", "cuda"], no-default-feature = true }
stage-3 = {features = ["stage-3"], no-default-feature = true}
stage-3-gpu = {features = ["stage-3", "cuda"], no-default-feature = true }
